// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | GenericTextSlice
  | ContactFormSlice
  | CustomerLogosSlice
  | PeopleSlice
  | StaticBigPictureSlice
  | MobileVideoSlice
  | BigVideoSlice
  | HeroSlice
  | HeaderSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *AlternateGrid → Default → Primary → items*
 */
export interface AlternateGridSliceDefaultPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *AlternateGrid → Image Right → Primary → items*
 */
export interface AlternateGridSliceImageRightPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceImageRightPrimaryItemsItem>
  >;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<AlternateGridSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Primary content in *BigVideo → Default → Primary*
 */
export interface BigVideoSliceDefaultPrimary {
  /**
   * label field in *BigVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For jumping to sections of page
   * - **API ID Path**: big_video.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Eyebrow field in *BigVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_video.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *BigVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_video.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *BigVideo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_video.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Video Hosted field in *BigVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: big_video.default.primary.video_hosted
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_hosted: prismic.LinkToMediaField;

  /**
   * Video Embedded field in *BigVideo → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: big_video.default.primary.video_embedded
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_embedded: prismic.EmbedField;
}

/**
 * Default variation for BigVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BigVideo*
 */
type BigVideoSliceVariation = BigVideoSliceDefault;

/**
 * BigVideo Shared Slice
 *
 * - **API ID**: `big_video`
 * - **Description**: BigVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigVideoSlice = prismic.SharedSlice<
  "big_video",
  BigVideoSliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Image field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * paragraph field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * buttonLink field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → AlignLeft → Primary*
 */
export interface CallToActionSliceAlignLeftPrimary {
  /**
   * Image field in *CallToAction → AlignLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.alignLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *CallToAction → AlignLeft → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.alignLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * paragraph field in *CallToAction → AlignLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.alignLeft.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * buttonLink field in *CallToAction → AlignLeft → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action.alignLeft.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * AlignLeft variation for CallToAction Slice
 *
 * - **API ID**: `alignLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceAlignLeft = prismic.SharedSliceVariation<
  "alignLeft",
  Simplify<CallToActionSliceAlignLeftPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceAlignLeft;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Fillout Form ID field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fillout_form_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fillout_form_id: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *CustomerLogos → Default → Primary → logos*
 */
export interface CustomerLogosSliceDefaultPrimaryLogosItem {
  /**
   * image field in *CustomerLogos → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.logos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *CustomerLogos → Default → Primary → logos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.logos[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *CustomerLogos → Default → Primary*
 */
export interface CustomerLogosSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *CustomerLogos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  eyebrowHeadline: prismic.RichTextField;

  /**
   * callToActionLink field in *CustomerLogos → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;

  /**
   * logos field in *CustomerLogos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<
    Simplify<CustomerLogosSliceDefaultPrimaryLogosItem>
  >;
}

/**
 * Default variation for CustomerLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomerLogosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CustomerLogos*
 */
type CustomerLogosSliceVariation = CustomerLogosSliceDefault;

/**
 * CustomerLogos Shared Slice
 *
 * - **API ID**: `customer_logos`
 * - **Description**: CustomerLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSlice = prismic.SharedSlice<
  "customer_logos",
  CustomerLogosSliceVariation
>;

/**
 * Primary content in *GenericText → Default → Primary*
 */
export interface GenericTextSliceDefaultPrimary {
  /**
   * Content field in *GenericText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: generic_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Last Updated field in *GenericText → Default → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: generic_text.default.primary.last_updated
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  last_updated: prismic.TimestampField;
}

/**
 * Default variation for GenericText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GenericTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GenericTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GenericText*
 */
type GenericTextSliceVariation = GenericTextSliceDefault;

/**
 * GenericText Shared Slice
 *
 * - **API ID**: `generic_text`
 * - **Description**: GenericText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GenericTextSlice = prismic.SharedSlice<
  "generic_text",
  GenericTextSliceVariation
>;

/**
 * Item in *Header → Default → Primary → Jump Links*
 */
export interface HeaderSliceDefaultPrimaryJumpLinksItem {
  /**
   * Anchor field in *Header → Default → Primary → Jump Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.jump_links[].anchor
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  anchor: prismic.LinkField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Logo field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Jump Links field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.jump_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  jump_links: prismic.GroupField<
    Simplify<HeaderSliceDefaultPrimaryJumpLinksItem>
  >;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Item in *Hero → Default → Primary → buttons*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Destination field in *Hero → Default → Primary → buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].destination
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination: prismic.LinkField;

  /**
   * Default field in *Hero → Default → Primary → buttons*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.buttons[].default
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  default: prismic.BooleanField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>;

  /**
   * Start Colour field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.start_colour
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  start_colour: prismic.ColorField;

  /**
   * End Colour field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.end_colour
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  end_colour: prismic.ColorField;

  /**
   * label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For jumping to sections of page
   * - **API ID Path**: hero.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *MobileVideo → Default → Primary*
 */
export interface MobileVideoSliceDefaultPrimary {
  /**
   * label field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For jumping to sections of page
   * - **API ID Path**: mobile_video.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Eyebrow field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Video Hosted field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.video_hosted
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_hosted: prismic.LinkToMediaField;

  /**
   * Video Embedded field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.video_embedded
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_embedded: prismic.EmbedField;

  /**
   * Start Colour field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.start_colour
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  start_colour: prismic.ColorField;

  /**
   * End Colour field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.end_colour
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  end_colour: prismic.ColorField;

  /**
   * Video Placement field in *MobileVideo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.default.primary.video_placement
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  video_placement: prismic.SelectField<"Left" | "Right">;
}

/**
 * Default variation for MobileVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MobileVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MobileVideoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MobileVideo → NoBar → Primary*
 */
export interface MobileVideoSliceNoBarPrimary {
  /**
   * label field in *MobileVideo → NoBar → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For jumping to sections of page
   * - **API ID Path**: mobile_video.noBar.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Eyebrow field in *MobileVideo → NoBar → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.noBar.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *MobileVideo → NoBar → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.noBar.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *MobileVideo → NoBar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.noBar.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Video Hosted field in *MobileVideo → NoBar → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.noBar.primary.video_hosted
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_hosted: prismic.LinkToMediaField;

  /**
   * Video Embedded field in *MobileVideo → NoBar → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.noBar.primary.video_embedded
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_embedded: prismic.EmbedField;

  /**
   * Video Placement field in *MobileVideo → NoBar → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_video.noBar.primary.video_placement
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  video_placement: prismic.SelectField<"Left" | "Right">;
}

/**
 * NoBar variation for MobileVideo Slice
 *
 * - **API ID**: `noBar`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MobileVideoSliceNoBar = prismic.SharedSliceVariation<
  "noBar",
  Simplify<MobileVideoSliceNoBarPrimary>,
  never
>;

/**
 * Slice variation for *MobileVideo*
 */
type MobileVideoSliceVariation =
  | MobileVideoSliceDefault
  | MobileVideoSliceNoBar;

/**
 * MobileVideo Shared Slice
 *
 * - **API ID**: `mobile_video`
 * - **Description**: MobileVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MobileVideoSlice = prismic.SharedSlice<
  "mobile_video",
  MobileVideoSliceVariation
>;

/**
 * Item in *People → Default → Primary → People*
 */
export interface PeopleSliceDefaultPrimaryPeopleItem {
  /**
   * Name field in *People → Default → Primary → People*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.people[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Bio field in *People → Default → Primary → People*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.people[].bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Photo field in *People → Default → Primary → People*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.people[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Role field in *People → Default → Primary → People*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.people[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;
}

/**
 * Item in *People → threeColumns → Primary → People*
 */
export interface PeopleSliceThreeColumnsPrimaryPeopleItem {
  /**
   * Name field in *People → threeColumns → Primary → People*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.threeColumns.primary.people[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Bio field in *People → threeColumns → Primary → People*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.threeColumns.primary.people[].bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Photo field in *People → threeColumns → Primary → People*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: people.threeColumns.primary.people[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Role field in *People → threeColumns → Primary → People*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.threeColumns.primary.people[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;
}

/**
 * Primary content in *People → Default → Primary*
 */
export interface PeopleSliceDefaultPrimary {
  /**
   * Label field in *People → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For jumping to sections of page
   * - **API ID Path**: people.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Eyebrow field in *People → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *People → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * People field in *People → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.people[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  people: prismic.GroupField<Simplify<PeopleSliceDefaultPrimaryPeopleItem>>;
}

/**
 * Default variation for People Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PeopleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PeopleSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *People → threeColumns → Primary*
 */
export interface PeopleSliceThreeColumnsPrimary {
  /**
   * Label field in *People → threeColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For jumping to sections of page
   * - **API ID Path**: people.threeColumns.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Eyebrow field in *People → threeColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.threeColumns.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *People → threeColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.threeColumns.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * People field in *People → threeColumns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: people.threeColumns.primary.people[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  people: prismic.GroupField<
    Simplify<PeopleSliceThreeColumnsPrimaryPeopleItem>
  >;
}

/**
 * threeColumns variation for People Slice
 *
 * - **API ID**: `threeColumns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PeopleSliceThreeColumns = prismic.SharedSliceVariation<
  "threeColumns",
  Simplify<PeopleSliceThreeColumnsPrimary>,
  never
>;

/**
 * Slice variation for *People*
 */
type PeopleSliceVariation = PeopleSliceDefault | PeopleSliceThreeColumns;

/**
 * People Shared Slice
 *
 * - **API ID**: `people`
 * - **Description**: People
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PeopleSlice = prismic.SharedSlice<"people", PeopleSliceVariation>;

/**
 * Primary content in *StaticBigPicture → Default → Primary*
 */
export interface StaticBigPictureSliceDefaultPrimary {
  /**
   * label field in *StaticBigPicture → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For jumping to sections of page
   * - **API ID Path**: static_big_picture.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Eyebrow field in *StaticBigPicture → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: static_big_picture.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *StaticBigPicture → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: static_big_picture.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *StaticBigPicture → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: static_big_picture.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *StaticBigPicture → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: static_big_picture.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Start Colour field in *StaticBigPicture → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: static_big_picture.default.primary.start_colour
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  start_colour: prismic.ColorField;

  /**
   * End Colour field in *StaticBigPicture → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: static_big_picture.default.primary.end_colour
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  end_colour: prismic.ColorField;
}

/**
 * Default variation for StaticBigPicture Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaticBigPictureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StaticBigPictureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StaticBigPicture*
 */
type StaticBigPictureSliceVariation = StaticBigPictureSliceDefault;

/**
 * StaticBigPicture Shared Slice
 *
 * - **API ID**: `static_big_picture`
 * - **Description**: StaticBigPicture
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaticBigPictureSlice = prismic.SharedSlice<
  "static_big_picture",
  StaticBigPictureSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimaryItemsItem,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceImageRightPrimaryItemsItem,
      AlternateGridSliceImageRightPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageRight,
      BigVideoSlice,
      BigVideoSliceDefaultPrimary,
      BigVideoSliceVariation,
      BigVideoSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceAlignLeftPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceAlignLeft,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      CustomerLogosSlice,
      CustomerLogosSliceDefaultPrimaryLogosItem,
      CustomerLogosSliceDefaultPrimary,
      CustomerLogosSliceVariation,
      CustomerLogosSliceDefault,
      GenericTextSlice,
      GenericTextSliceDefaultPrimary,
      GenericTextSliceVariation,
      GenericTextSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimaryJumpLinksItem,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MobileVideoSlice,
      MobileVideoSliceDefaultPrimary,
      MobileVideoSliceNoBarPrimary,
      MobileVideoSliceVariation,
      MobileVideoSliceDefault,
      MobileVideoSliceNoBar,
      PeopleSlice,
      PeopleSliceDefaultPrimaryPeopleItem,
      PeopleSliceDefaultPrimary,
      PeopleSliceThreeColumnsPrimaryPeopleItem,
      PeopleSliceThreeColumnsPrimary,
      PeopleSliceVariation,
      PeopleSliceDefault,
      PeopleSliceThreeColumns,
      StaticBigPictureSlice,
      StaticBigPictureSliceDefaultPrimary,
      StaticBigPictureSliceVariation,
      StaticBigPictureSliceDefault,
    };
  }
}
