// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  big_video: dynamic(() => import("./BigVideo")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact_form: dynamic(() => import("./ContactForm")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  generic_text: dynamic(() => import("./GenericText")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  mobile_video: dynamic(() => import("./MobileVideo")),
  people: dynamic(() => import("./People")),
  static_big_picture: dynamic(() => import("./StaticBigPicture")),
};
